#!/bin/bash

source env.sh

docker tag $DOCKER_IMAGE $DOCKER_REGISTRY:5000/$DOCKER_IMAGE
docker push $DOCKER_REGISTRY:5000/$DOCKER_IMAGE
docker rmi $DOCKER_REGISTRY:5000/$DOCKER_IMAGE

export DOCKER_IMAGE=$DOCKER_IMAGE:arm
docker tag $DOCKER_IMAGE $DOCKER_REGISTRY:5000/$DOCKER_IMAGE
docker push $DOCKER_REGISTRY:5000/$DOCKER_IMAGE
docker rmi $DOCKER_REGISTRY:5000/$DOCKER_IMAGE