#!/bin/bash

source env.sh
DOCKER_IMAGE=$DOCKER_IMAGE:slim

docker tag $DOCKER_IMAGE $DOCKER_REGISTRY:5000/$DOCKER_IMAGE
docker push $DOCKER_REGISTRY:5000/$DOCKER_IMAGE
docker rmi $DOCKER_REGISTRY:5000/$DOCKER_IMAGE


source env.sh
DOCKER_IMAGE=$DOCKER_IMAGE:arm-slim

docker tag $DOCKER_IMAGE $DOCKER_REGISTRY:5000/$DOCKER_IMAGE
docker push $DOCKER_REGISTRY:5000/$DOCKER_IMAGE
docker rmi $DOCKER_REGISTRY:5000/$DOCKER_IMAGE